# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=90)),
                ('hero', models.CharField(max_length=90)),
                ('heroine', models.CharField(max_length=90)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
